# Generated by Django 2.1.2 on 2018-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
